# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: UNdecided
description: This is where the description of your site will go. You should change it by editing the _config.yml file. It can be as long as you like! Happy blogging... ❤
github_username: nithishdivakar

# Email and twitter are optional:
email: 
twitter_username: nithishdivakar

# Set this to true to get LaTeX math equation support
use_math: true 

# Everything below here can be ignored, unless you want to change the theme entirely

# theme: minima

sass:
  style: compressed
  sass_dir: _sass

  # style : nested (default), compact, compressed, expanded
  #         :nested, :compact, :compressed, :expanded also works
  # see http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  # on a typical twitter bootstrap stats are :
  # nested 138,7kB, compact 129,1kB, expanded 135,9 kB, compressed 122,4 kB
  # style: compressed

plugins:
  - jekyll-feed

show_excerpts: true

# titles_from_headings:
#   enabled:     true
#   strip_title: true
#   collections: true

# highlighter: rouge
highlighter: none

markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
#  syntax_highlighter: rouge
  syntax_highlighter_opts:
    disable: true

# extra
exclude:
  - _posts/*.ipynb
  - _posts/*.py
  - _posts/*.txt

defaults:
  - scope:
      path: "images"
    values:
      image: true
